name: Warmly welcome!
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Warmly welcome!
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "weeelcome"
        env:
          GITHUB_TOKEN: ${{ sectrts.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
